apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x9pmvwdsj-nodejs 
  janus-idp.io/tekton: x9pmvwdsj-nodejs
  backstage.io/kubernetes-id: x9pmvwdsj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x9pmvwdsj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  