apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x9pmvwdsj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x9pmvwdsj-nodejs 
  name: x9pmvwdsj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x9pmvwdsj-nodejs 
